#!/bin/bash

## Description: Run ajaxcatalog PHPUnit tests
## Usage: test [flags]
## Example: ddev test
## Example: ddev test --filter=testIsSaleForZeroPrice
## ProjectTypes: magento

cd /var/www/html/openmage
php vendor/bin/phpunit --configuration /var/www/html/phpunit.xml "$@"
