#!/bin/bash

## Description: Run PHPUnit tests
## Usage: test [flags]
## Example: ddev test
## Example: ddev test --filter=testMyFeature
## Example: ddev test --testdox
## ProjectTypes: magento

cd /var/www/html/openmage
php vendor/bin/phpunit --configuration /var/www/html/phpunit.xml "$@"
